server:
  port: 8000

spring:
  application:
    name: MS-API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-route-id: true
          routes:
            - id: patient-data-collector
              uri: lb://PatientDataCollector
              predicates:
                - Path=/conjunta/2p/vital-signs/**
              filters:
                - StripPrefix=2
            - id: health-analyzer
              uri: lb://HealthAnalyzer
              predicates:
                - Path=/conjunta/2p/health-analyzer/**
              filters:
                - StripPrefix=2
            - id: care-notifier
              uri: lb://CareNotifier
              predicates:
                - Path=/api/conjunta/2p/notification/**
              filters:
                - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
